package reference

import (
	"bytes"
	"encoding/csv"
	"math"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

func TestTargetsShareFixedBudgets(t *testing.T) {
	targets, err := Targets()
	if err != nil {
		t.Fatalf("Targets() error = %v", err)
	}

	wantNames := []string{
		"low-pass",
		"parametric-eq",
		"crossover",
		"deep-notch",
		"room-correction",
	}
	if len(targets) != len(wantNames) {
		t.Fatalf("len(Targets()) = %d, want %d", len(targets), len(wantNames))
	}

	for index, target := range targets {
		if target.Name != wantNames[index] {
			t.Errorf(
				"Targets()[%d].Name = %q, want %q",
				index,
				target.Name,
				wantNames[index],
			)
		}

		if len(target.Prototype) != prototypeLength {
			t.Errorf(
				"%s prototype length = %d, want %d",
				target.Name,
				len(target.Prototype),
				prototypeLength,
			)
		}

		if len(target.DelayWeight) != FFTSize/2+1 {
			t.Errorf(
				"%s weight length = %d, want %d",
				target.Name,
				len(target.DelayWeight),
				FFTSize/2+1,
			)
		}

		totalWeight := 0.0

		for _, weight := range target.DelayWeight {
			if weight < 0 || math.IsNaN(weight) || math.IsInf(weight, 0) {
				t.Errorf("%s has invalid weight %g", target.Name, weight)
			}

			totalWeight += weight
		}

		if totalWeight == 0 {
			t.Errorf("%s has zero total weight", target.Name)
		}
	}
}

func TestRunCoversEveryMethodAndMetric(t *testing.T) {
	rows, err := Run(0)
	if err != nil {
		t.Fatalf("Run() error = %v", err)
	}

	const methodCount = 4
	if len(rows) != 5*methodCount {
		t.Fatalf("len(Run()) = %d, want %d", len(rows), 5*methodCount)
	}

	for _, row := range rows {
		if row.SampleRate != SampleRate ||
			row.Taps != TapCount ||
			row.FFTSize != FFTSize ||
			row.DelayBudget != DelayBudget {
			t.Errorf("%s/%s has inconsistent budget: %+v", row.Target, row.Method, row)
		}

		if row.Runtime != 0 {
			t.Errorf("%s/%s runtime = %v, want zero", row.Target, row.Method, row.Runtime)
		}

		finite := []float64{
			row.RelativeMagnitudeError,
			row.RMSMagnitudeErrorDB,
			row.MaxMagnitudeErrorDB,
			row.MeanGroupDelay,
			row.GroupDelayRipple,
			row.PeakGroupDelay,
			row.EnergyCentroid,
			row.PrePeakEnergyRatio,
			row.CoefficientPeak,
			row.CoefficientRangeDB,
			row.ConstraintViolation,
		}
		for _, value := range finite {
			if math.IsNaN(value) || math.IsInf(value, 0) {
				t.Errorf(
					"%s/%s has non-finite metric %g",
					row.Target,
					row.Method,
					value,
				)
			}
		}

		if row.PrePeakEnergyRatio < 0 || row.PrePeakEnergyRatio > 1 {
			t.Errorf(
				"%s/%s pre-peak ratio = %g",
				row.Target,
				row.Method,
				row.PrePeakEnergyRatio,
			)
		}
	}

	assertCommittedQualityCSV(t, rows)
}

func TestWriteCSV(t *testing.T) {
	rows := []Row{{
		Target:                 "fixture",
		Method:                 "method",
		SampleRate:             SampleRate,
		Taps:                   TapCount,
		FFTSize:                FFTSize,
		DelayBudget:            DelayBudget,
		Iterations:             2,
		RelativeMagnitudeError: 0.25,
	}}

	var output bytes.Buffer
	if err := WriteCSV(&output, rows); err != nil {
		t.Fatalf("WriteCSV() error = %v", err)
	}

	records, err := csv.NewReader(strings.NewReader(output.String())).ReadAll()
	if err != nil {
		t.Fatalf("read generated CSV: %v", err)
	}

	if len(records) != 2 {
		t.Fatalf("CSV row count = %d, want 2", len(records))
	}

	if len(records[0]) != len(csvHeader) ||
		len(records[1]) != len(csvHeader) {
		t.Fatalf(
			"CSV column counts = %d/%d, want %d",
			len(records[0]),
			len(records[1]),
			len(csvHeader),
		)
	}

	if records[1][0] != "fixture" || records[1][1] != "method" {
		t.Errorf("CSV identity columns = %q/%q", records[1][0], records[1][1])
	}
}

func TestMarkdownTable(t *testing.T) {
	rows := []Row{
		{
			Target:                 "parametric-eq",
			Method:                 "budde-iterative",
			Runtime:                1500,
			RelativeMagnitudeError: 0.0125,
			MeanGroupDelay:         4.25,
			PrePeakEnergyRatio:     0.5,
		},
		{
			Target: "parametric-eq",
			Method: "phase-interpolation",
		},
	}

	table := markdownTable(rows)
	wants := []string{
		"| parametric EQ | Budde iterative",
		"|               | phase interpolation",
		"1.25000%",
		"4.25",
		"50.00%",
		"0.00 ms",
	}

	for _, want := range wants {
		if !strings.Contains(table, want) {
			t.Errorf("markdownTable() does not contain %q:\n%s", want, table)
		}
	}
}

func TestRunRejectsNegativeTrials(t *testing.T) {
	if _, err := Run(-1); err == nil {
		t.Fatal("Run(-1) error = nil")
	}
}

func assertCommittedQualityCSV(t *testing.T, rows []Row) {
	t.Helper()

	var generated bytes.Buffer
	if err := WriteCSV(&generated, rows); err != nil {
		t.Fatalf("WriteCSV() error = %v", err)
	}

	_, source, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller() failed")
	}

	path := filepath.Join(
		filepath.Dir(source),
		"..",
		"..",
		"docs",
		"reference-results.csv",
	)

	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read committed reference CSV: %v", err)
	}

	got := qualityCSV(t, generated.Bytes())

	want := qualityCSV(t, committed)
	if got != want {
		t.Fatal(
			"committed quality results are stale; run `just compare` " +
				"and review the metric changes",
		)
	}
}

func qualityCSV(t *testing.T, input []byte) string {
	t.Helper()

	records, err := csv.NewReader(bytes.NewReader(input)).ReadAll()
	if err != nil {
		t.Fatalf("parse reference CSV: %v", err)
	}

	for index := 1; index < len(records); index++ {
		records[index][7] = "0"
	}

	var output bytes.Buffer

	writer := csv.NewWriter(&output)

	if err := writer.WriteAll(records); err != nil {
		t.Fatalf("normalise reference CSV: %v", err)
	}

	return output.String()
}
